### ISSUE TITLE
Add a timeout to the HTTP request

### ISSUE THREAD

**Issue by philipithomas** [masonj88/passwordChecker#2]
Thanks for the library!

Because this library blocks a user request, it would be helpful to add a timeout to the HTTP request. I'd personally use 2 seconds, but this could be user-configurable.

**Comment by masonj5n** [comment]
Ya good catch. Let's just do a hard timeout of 2 seconds for now, should just be replacing the default http client with one that has a timeout of 2 seconds set.

**Comment by masonj5n** [comment]
Added a default timeout of 2 seconds to the calls to haveibeenpwned.

**Comment by philipithomas** [comment]
Thank you for the quick work!
